[package]
name = "dp_rss"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
chrono = "0.4.41"
rss = { version = "2.0.12", features = ["validation"] }
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
